# -*- coding: utf-8 -*-
"""data_access.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cax1OvkZ4jHKVGvs6b3dbUIHFgwDGscT

### American Community Survey Data Access

*   input: zipcode, year
*   output: education attainment / Median Household Income / 
*  Your API key is 7871246f33d0024d3ed2f6bb86cf09174ceff816

#### I used 5 years data, since only in this dataset, there are data based on zipcode (2009 - 2017)
#### Lots of variables could be found here:

https://factfinder.census.gov/faces/nav/jsf/pages/community_facts.xhtml
Population / Median Age / Number of Companies / Educational Attainment: Percent high school graduate or higher / Total housing units / Median Household Income / Foreign Born Population / Individuals below poverty level / Race and Hispanic Origin / Veterans

"""

!pip install census
!pip install us

#test
from census import Census
from us import states

c = Census("7871246f33d0024d3ed2f6bb86cf09174ceff816", 2017)
c.acs5.zipcode(('NAME', 'B25034_010E'), "48105")

#function input prep
income_code = "B19013_001E" #medium FAMILY INCOME IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS)
education_code = "B15003_022E" #Annotation of Estimate!!Total!!Bachelor's degree
population_code = "B01003_001E"
codes = (income_code, education_code, population_code)
code_dic = {income_code:"medium household income", education_code:"number of 25-above with bachelor degree", population_code:"population"}

def get_info_by_zip5(year, codes, zip5, code_dic):
  c = Census("7871246f33d0024d3ed2f6bb86cf09174ceff816", year)
  res = c.acs5.zipcode(codes , zip5)
  #return res
  for k,v in res[0].items():
    if k in code_dic.keys():
      print(code_dic[k] + " : " + str(v))

#test function
get_info_by_zip5(2017, codes, "48105", code_dic)
#res[0]

"""## geographic dataset 


- input: state
- output: all 5-digits zipcode in state
"""

